name: xcsp-launcher
base: core22
version: '0.1.0' # Cette version sera remplacée dynamiquement
summary: A unified launcher for XCSP3 solvers
description: |
  XCSP Launcher is a CLI tool to manage, compile, and solve XCSP3 models easily.

grade: stable
confinement: strict

apps:
  xcsp:
    command: bin/xcsp
    plugs: [home, network]

parts:
  xcsp:
    plugin: dump
    source: ./dist/
    stage:
      - xcsp
    organize:
      xcsp: bin/xcsp
      configs: share/xcsp/configs