name: Build and Release Binaries

on:
  workflow_run:
    workflows: [Python Tests]
    types:
      - completed
  push:
    tags:
      - "v*"

jobs:
  build-binaries:
    name: Build Binaries and Packages
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install tools
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install . 
          
          if [[ "${{ runner.os }}" == "Linux" ]]; then
            sudo apt-get update
            sudo apt-get install -y ruby ruby-dev build-essential fpm snapcraft
            sudo gem install --no-document fpm
          fi
          
          if [[ "${{ runner.os }}" == "Windows" ]]; then
            choco install make --yes
          fi

      - name: Build binary
        run: make pyinstaller

      - name: Generate snapcraft.yaml, snap and deb package (Linux only)
        if: matrix.os == 'ubuntu-latest'
        run: |
          make deb
          make snap
          snapcraft login --with ${{ secrets.SNAPCRAFT_LOGIN_FILE }}
          snapcraft push *.snap
      - name: Create Chocolatey package (Windows only)
        if: matrix.os == 'windows-latest'
        shell: pwsh
        run: |
          mkdir -p chocolatey/tools
          Copy-Item dist/xcsp.exe chocolatey/tools/xcsp.exe
          Copy-Item chocolatey/chocolateyInstall.ps1 chocolatey/tools/chocolateyInstall.ps1
          $nuspec = Get-Content chocolatey/xcsp-launcher.nuspec.template
          $nuspec = $nuspec -replace '__VERSION__', '${{ github.ref_name }}'
          $nuspec | Set-Content chocolatey/xcsp-launcher.nuspec
          choco pack chocolatey/xcsp-launcher.nuspec
          choco push chocolatey/xcsp-launcher.*.nupkg --api-key ${{ secrets.CHOCOLATEY_API_KEY }} --source https://push.chocolatey.org/
      - name: Create Homebrew Formula (macOS only)
        if: matrix.os == 'macos-latest'
        run: |
          make brew
          make publish-brew
      - name: Upload binaries to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/xcsp* 
            *.deb
            *.snap
            chocolatey/*.nupkg
            *.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
