name: Python Tests
on: [push] # Can also put pull_request here, but then we dont run it when directly pushing to master
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ '3.10', '3.11', '3.12', '3.13' ]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          cache-dependency-path: |
              requirements.txt
              setup.cfg
              pyproject.toml
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pytest-xdist
          pip install psutil
          pip install . 
          make deb
          sudo dpkg -i xcsp-launcher*.deb
          xcsp --bootstrap
      - name: Test with pytest
        run: |
          python -m pytest -n 4 tests/